pinterest/pymemcache

pymemcache/client.py
pymemcache/test/test_client.py

It doesn't seem needed to have instance local-side effects
especially around a shared buffer (having it exists makes
thread-safety and/or thread-safe clients that much harder to
achieve).

Remove instance local buffer

---

pymemcache/client.py
pymemcache/pool.py

It can be quite useful to allow the lock that the pool
uses to be specified to be something other than the default
threading lock class/type. This can be especially useful when
eventlet (or gevent or other) are used which have there own
special lock type that connects into there event-loop.

Allow the pool lock to be specialized

---

pymemcache/client/base.py
pymemcache/client/hash.py
pymemcache/test/test_client.py
pymemcache/test/utils.py

Fixes #58 . Basic `x = y` renaming.
Also `delete_many` was missing on some of the Client classes, so I added it and tests for it.

Multi methods

---

pymemcache/client/hash.py

I was doing some benchmarking and I needed this patch to be able to plug in ewdurbin/clandestined-python as the hash implementation.
In passing, there's a separate issue where pymemcache calls the relevant method `get_node`, but clandestined-python calls it `find_node`.
Thanks for your time.

make the hasher class pluggable in HashClient

---

pymemcache/client/hash.py
pymemcache/test/test_client_hash.py

This fixes the hashclient when `ignore_exc` is set to `True`.   I will make a separate PR on top of this that will get no servers found put into the retry cycle.  So if all servers are down but we haven't waited our defined time it wont blow up either.  Just need to think about that use case a little more :)

hashclient ignores exceptions when no servers are found

---

README.rst

with the significant amount of `python-clandestined` source code copied into the `HashClient`, I would appreciate accreditation somewhere high-level than in the depths of source code.

Add myself to credits.

---

pymemcache/client/hash.py
pymemcache/test/test_client_hash.py

This pull fixes 2 small issues.
The first is an exception thrown when `retry_attempts` to 0 instead of -1 to disable it. It would throw a key error due to `self._failed_clients` not being populated.
The second issue is an exception regarding the use of % while creating output log and `client.server` being a tuple instead of a string.
Included testcase fails on current master and succeeds on this branch.

Fixed bugs caused by setting retry attempts to 0 on HashClient

---

pymemcache/client/base.py
pymemcache/test/test_client.py

As the title says, added the version command, although for the wrong reasons. 
We found it useful as a "NoOp" command during health checks.
Others may find it useful to actually get the server version.

Implemented VERSION command in Client and PooledClient

---

pymemcache/client/base.py

Addresses issue #92
In Ubuntu's (14.04) version of memecached packaged with the OS the
version STAT line contains a fourth value due to a space. This breaks
the expected triplet pattern and incorrectly caused an exception.

Handle stats not conforming to the triplet format

---

pymemcache/client/base.py
pymemcache/test/test_client.py

Addresses issue #94 
Fixed evictions value conversion in base.py.  
- evictions stat value was incorrectly being compared to “b’on’” previously, which resulted in a boolean. The fix makes the conversion default to int, which is in line with other numeric stats values.
Augmented test_stats_conversions() test case in test_client.py to test evictions value conversion

Fixed stats evictions value conversion

---

README.rst

pylibmc v1.5.1 includes a serialization API: http://sendapatch.se/projects/pylibmc/reference.html#pylibmc.Client.serialize

update comparison to pylibmc

---

.gitignore
pymemcache/__init__.py
pymemcache/client/base.py
pymemcache/test/test_client.py
pymemcache/test/test_client_hash.py
tox.ini

Running `tox` left the project with some syntax and build errors. This cleans it up a little so that cloning and running `tox` should run fine

Syntax and build

---

pymemcache/client/base.py
pymemcache/test/test_client.py
pymemcache/test/utils.py

I thought it would be a nice feature to be able to do:
```python
foo = client.get('foo', default=b'bar').decode()
```
instead of:
```python
foo = client.get('foo')
if foo is None:
foo = b'foo'
foo.decode()
```

Added default parameter support for "get" and "gets" methods in Client

---

pymemcache/client/base.py

* Quote the key so it's easier to realize e.g. trailing spaces
* Point out newlines are bad as well as spaces
* Capitalize ASCII

Improve MemcacheIllegalInputError messages

---

pymemcache/serde.py
pymemcache/test/test_serde.py
tox.ini

* Add linting on Python 3 too - normal environment failed for me initially since my `tox` is installed with Python 3 and so `flake8` failed on the syntax errors in `serde`
* Fix `serde` to be importable in Python 3
* Add some tests for `serde`

Lint on Python 3 too

---

setup.cfg

Prevent `WC1 None [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.`, as per pytest-dev/pytest#567.

Prevent pytest-warning on pytest 3.0+

---

pymemcache/client/base.py
pymemcache/test/test_client.py

Create one function for each extra parseable type to make it clear there are different types in the stats response, and to stop wasting memory on making several `lambda`s that all do the same thing.
Also improve test coverage of the parsing.

Improve stats parsing

---

pymemcache/test/test_client.py
pymemcache/test/utils.py

There is a slight issue with the `MockMemcacheClient` where it's not using the serializer/deserializer properly and extracting out values and flags. 
This PR fixes and adds a few tests around this behaviour

Fix MockMemcacheClient serialization/deserialization

---

.gitignore
pymemcache/client/base.py
pymemcache/test/test_client.py
pymemcache/test/utils.py
tox.ini

See #117 
This fixes an error where one lonely unicode character can _hide_ in a key or value. We need to make sure to raise the illegal input when this happens.

Fix #117, illegal unicode character in middle of key (or value now)

---

pymemcache/serde.py

Using cPickle can result in big speed boosts according to the [Python docs on `pickle`](https://docs.python.org/2/library/pickle.html#relationship-to-other-python-modules)
> The pickle module has an optimized cousin called the cPickle module. As its name implies, cPickle is written in C, so it can be up to 1000 times faster than pickle
For Python 2, you need to import `cPickle` explicitly. In Python 3, `import pickle` chooses `cPickle` automatically if it's available.

Use cPickle if available on Python 2

---

README.rst
docs/getting_started.rst
pymemcache/client/base.py
pymemcache/client/hash.py
pymemcache/client/rendezvous.py
pymemcache/test/test_client.py
pymemcache/test/test_client_hash.py
pymemcache/test/test_integration.py
pymemcache/test/utils.py
test-requirements.txt
tox.ini

memcached's ASCII protocol supports unicode keys, so lets support them
as well. Since using unicode keys for memcache is uncommon and to
preserve the previous behavior disable support by default.

Add optional support for unicode keys

---

pymemcache/serde.py
pymemcache/test/test_integration.py
pymemcache/test/test_serde.py

I was looking at trying to use/resurrect django-pymemcache, however in trying to update it and get tests working on it - pymemcache serialization seems to have some issues with byte/unicode strings. This is mostly a Python 3 problem, but could cause problems elsewhere.
To solve this problem, I've taken a similar approach to https://github.com/linsomniac/python-memcached/pull/100/files:
- Only byte strings get serialized without a flag
- Unicode strings get serialized with a different text flag
- Only specific builtin types get flags added, everything else gets pickled
Also `test_serde.py` wasn't being picked up with pytest as it didn't have a decorator - so I've added that.

Python 3 serialization fixes, serialization improvements

---

pymemcache/client/hash.py

this note is misleading, as the hasher is expected to expose a `get_node`
method. clandestined's `RendezvousHash` does not implement this method.
when clandestined's implementation was copied into pymemcached in commit
cff5abfad59baa593996fe7e240fd3944e2c4af2, the method was renamed from
`find_node` to `get_node`, breaking compatibility.

remove suggestion to use python-clandestined

---

pymemcache/client/base.py
pymemcache/test/test_client.py

Memcache does not support setting keys with null byte, newline, carriage return. This adds support for checking the key to ensure the key is valid.
Setting keys with these returns the following exception:
```python
>>> client.set('\r\ntest', 'foo')
File "<stdin>", line 1, in <module>
File "lib/memcache.py", line 139, in set
return super(Client, self).set(key, value, expire=expire, noreply=noreply)
File .../env/lib/python2.7/site-packages/pymemcache/client/base.py", line 256, in set
return self._store_cmd(b'set', key, expire, noreply, value)
File .../env/lib/python2.7/site-packages/pymemcache/client/base.py", line 747, in _store_cmd
self._raise_errors(line, name)
File ".../env/lib/python2.7/site-packages/pymemcache/client/base.py", line 654, in …
```

Raising MemcacheIllegalInputError when key contains null byte, newline, or carriage return

---

setup.py
tox.ini

As decided in https://github.com/pinterest/pymemcache/issues/139, killing support for python 2.6

Kill python 2.6

---

pymemcache/client/hash.py
pymemcache/test/test_client_hash.py

#The documentation for `ignore_exc` says it will treat memcache/network errors as cache misses (i.e. `None` for reads and `False` for writes).
However the short-circuit path for when no client can be used (because they're all marked as down/bad) always returns `False`. This fix, changes the behaviour to return each command's default value instead.
I actually stumbled upon this because I wanted to inspect some behaviour in a system without cache so I stopped all memcached nodes. Our code looked something like this:
```python
data = memcached_client.get(key)
if data is None:
return fetch_from_database(key)
else:
return json.loads(data)
```
What happened was that every once in a while I would see a stacktrace because the `json.loads(data)` call would fail with a `TypeError` because it tries …

Return default value instead of False when all clients are down

---

pymemcache/client/base.py
pymemcache/test/test_client.py

Stats cachedump has a different input and output format compared to
most stats commands. Previously this would fail with a cryptic error.
Fixes issue #103

Add support for stats cachedump

---

pymemcache/client/base.py

Fixed a small typo in the doc string of the pooled client

---

tox.ini

Whenever you run tox locally, it builds the docs. This has the effect of building a bunch of new files that need cleaning.
Readthedocs builds the docs by itself, it doesn't need them to be checked in anyway, so this makes sure tox.ini is idempotent and doesn't modify any local files.

Remove docs from being run when you're running tests

---

README.rst

I would like to simplify the setup instructions as much as possible. There is no need to suggest 2 different ways to run tests. Since tox is idempotent, use it as sole method of running the tests.
If you have further ideas for simplifying docs, please let us know!

Simplify README for running tests. Only tox

---

setup.cfg
setup.py

Also fix a minor flake8 issue in `setup.py`.

Exclude well-known non-code paths from flake8

---

pymemcache/serde.py

Also include a forewarning note on Python "pickleableness".
This also allows easier changing as it's now a constant. While not perfect, it's certainly helpful for me at least!
The issue with version 0 is that some objects which *should* be pickleable are not.
Namely this scenario:
* An object defines `__getstate__` to select the state to be pickled and restored.
* This object contains a non-pickleable slotted object in an attribute value (ie defines `__slots__`)
* Said attribute happens to be specifically excluded from the state dictionary returned from `__getstate__` of it's parent, but alias, cPython with pickle version zero returns:
`*** TypeError: a class that defines __slots__ without defining __getstate__ cannot be pickled`
Fun stuff. Thanks for the lib.

Use only the highest, premium quality pickler available at runtime.

---

pymemcache/client/hash.py
pymemcache/test/test_client_hash.py

Libraries should raise library specific exceptions. Such as
MemcacheError. This enables users to easily catch exceptions generated
by library separate from other exceptions. Raising "Exception" forces
catching Exception and potentially masks all sorts of issues.

Don't Raise Generic Exception

---

pymemcache/test/test_utils.py
pymemcache/test/utils.py

The current MockMemcacheClient doesn't support storage of non-ascii strings as values, but the real Client does. Here's an example:
The real Client on a local memcached:
```
>>> from pymemcache.client import Client
>>> client = Client(('localhost', 11211))
>>> binary_str = msgpack.packb('123')
>>> binary_str
'\xa3123'
>>> client.set('foo', binary_str)
True
>>> client.get('foo')
'\xa3123'
```
And the MockMemcacheClient:
```
>>> from pymemcache.test.utils import MockMemcacheClient
>>> mock = MockMemcacheClient()
>>> mock.set('foo', binary_str)
File "<stdin>", line 1, in <module>
File "/Users/edwardlim/Documents/dev/python_envs/chuggs/lib/python2.7/site-packages/pymemcache/test/utils.py", line 92, in set
raise MemcacheIllegalInputError …
```

Have MockMemcacheClient support non-ascii strings

---

.travis.yml
pymemcache/client/hash.py
pymemcache/test/test_utils.py
setup.py
test-requirements.txt
tox.ini

* Test against python 3.5 and 3.6
* Run flake8 in travis
* Add missing python versions to travis config, previously some tests passed with:
ERROR: InterpreterNotFound: python2.6
SKIPPED:  py26: InterpreterNotFound: python2.6

Update testing matrix

---

.travis.yml
tox.ini

This is because `wheel` requires it *not* be `3.3.x`.
Of course, we can instead hack this to install some ancient wheel on an
ancient Python... but nobody should be running `3.3.x`, so it'd
just be cruft, at least in my garbage opinion ;)

Remove deprecated Python version. This makes tests fail at the moment.

---

ChangeLog.rst
pymemcache/client/base.py
pymemcache/client/hash.py
pymemcache/test/test_client.py
pymemcache/test/test_client_hash.py
pymemcache/test/utils.py

Failed `set_many` with django2.0.
```python
>>> from django.core.cache import cache
>>> cache.set_many({'aa': 1})
File "/usr/lib/python3.6/code.py", line 91, in runcode
exec(code, self.locals)
File "<console>", line 1, in <module>
File "/usr/local/lib/python3.6/dist-packages/ddtrace/contrib/django/cache.py", line 65, in wrapped
return method(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/django_elastipymemcache/memcached.py", line 43, in wrapper
return f(self, *args, **kwds)
File "/usr/local/lib/python3.6/dist-packages/django_elastipymemcache/memcached.py", line 135, in set_many
return super(ElastiPyMemCache, self).set_many(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/django/core/cache/backends/memcached.py", line 144, in …
```

fix django2.0

---

.travis.yml

Python 2.6 support was killed in https://github.com/pinterest/pymemcache/pull/142 but it looks like Travis is still trying to run tests against the py26 Tox environment (failing https://github.com/pinterest/pymemcache/pull/180, for example).

Remove py26 detritus from .travis.yml

---

pymemcache/client/base.py
pymemcache/test/test_client.py

`pymemcache.client.base.Client.set_many()` currently loops over its `values` dictionary and sends each key-value pair separately rather. This diff drops them in bulk into the fewest TCP packets in which they'll fit. If the overall approach meets your approval, I'll send a separate PR to do the same for `delete_many()`.
Using the expanded benchmarks from #180 and snipping output down to just the relevant lines, the current codebase yields these results:
```
$ pytest --verbose --capture=no --no-cov -m benchmark pymemcache/test --keys 100 --count 10000
========================================== test session starts ===========================================
platform darwin -- Python 2.7.15, pytest-3.7.4, py-1.6.0, pluggy-0.7.1 -- /Users/shargan/repos/pymemcache/.venv/bin/python …
```

Properly batch Client.set_many() calls

---

pymemcache/test/conftest.py
pymemcache/test/test_benchmark.py

The current benchmarks are fairly coarse and make it difficult to tell which methods are performant and which could use some work. This diff breaks them down more comprehensively and adds in `get_multi()` and `set_multi()` tests. Beware that these are slow (particularly on pylibmc).
Example output:
```
$ pytest --verbose --capture=no --no-cov -m benchmark pymemcache/test
================================================ test session starts =================================================
platform darwin -- Python 2.7.15, pytest-3.7.4, py-1.6.0, pluggy-0.7.1 -- /Users/shargan/repos/pymemcache/.venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/shargan/repos/pymemcache, inifile: setup.cfg
plugins: cov-2.5.1
collected 392 items / 380 deselected …
```

Split benchmarks by method and include get_multi and set_multi

---

.travis.yml

The previous directory-based caching directive worked fine, but using
the generic `pip` syntax is simpler and more future-proof.

Use simpler Travis pip caching syntax

---

pymemcache/client/base.py

While making the batching changes in #182 I noticed a few performance hot-spots.
1. `_check_key()` is called at least once on every single operation and was doing a lot of repeat or just inefficient work.
2. `_store_cmd()` was calculating and encoding `extra` and `expire` for every key/value pair even though they don't change (I didn't move this in the previous PR because I didn't want to muddy my intentions).
The first change is responsible for most of the performance increase, it affects every method, and the difference scales with key length. The second only impacts `set_many()` but in my 100-key tests was responsible for a decent 7.5% gain.
Benchmarks from master with irrelevant lines trimmed:
```
$ pytest --verbose --capture=no --no-cov -m benchmark pymemcache/test --keys 100 --count …
```

Improve _check_key() and _store_cmd() performance

---

.gitignore
.travis.yml
setup.py
test-requirements.txt
tox.ini

Travis's default base image doesn't support Python 3.7 very well so we
need to explicitly select the xenial distribution with sudo enabled.

Add official Python 3.7 support

---

pymemcache/client/base.py
pymemcache/test/test_benchmark.py

Essentially the same change as #182 but for `delete_many()` and its underlying `_misc_cmd()` method. This includes benchmarks for the delete methods.
Benchmarks for the current codebase with irrelevant lines trimmed:
```
$ pytest --verbose --capture=no --no-cov -m benchmark pymemcache/test --keys 100 --count 10000
================================================ test session starts =================================================
platform darwin -- Python 2.7.15, pytest-3.7.4, py-1.6.0, pluggy-0.7.1 -- /Users/shargan/repos/pymemcache/.venv/bin/python
pymemcache/test/test_benchmark.py::test_bench_delete[pymemcache] 0.296519994736
pymemcache/test/test_benchmark.py::test_bench_delete_multi[pymemcache] 27.9956350327
$ pytest --verbose --capture=no --no-cov -m benchmark pymemcache/test --keys …
```

Properly batch Client.delete_many() calls

---

pymemcache/client/base.py
pymemcache/test/test_client.py
pymemcache/test/test_integration.py
pymemcache/test/utils.py
test-requirements.txt

Previously python2 code using python-future to backport the py3 bytes
behavior would trigger the following exception:
code:
```python
from builtins import bytes as newbytes
from pymemcache.client.base import Client
client = Client(('localhost', 11211))
client.set(newbytes('key'), 'value')
```
Output:
```
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/site-packages/pymemcache/client/base.py", line 297, in set
return self._store_cmd(b'set', key, expire, noreply, value)
File "/usr/local/lib/python2.7/site-packages/pymemcache/client/base.py", line 770, in _store_cmd
key = self.check_key(key)
File "/usr/local/lib/python2.7/site-packages/pymemcache/client/base.py", line 251, in check_key
key_prefix=self.key_prefix)
File …
```

Fix support newbytes from future

---

docs/getting_started.rst
pymemcache/serde.py
pymemcache/test/test_integration.py
pymemcache/test/test_serde.py

It's unsafe to use the max pickle version when you are switching between
versions of python with different max versions.
Add a new function get_python_memcache_serializer_pickle_version that
returns a python_memcache_serializer with any pickle version.

Make pickle version for python_memcache_serializer adjustable

---

ChangeLog.rst

There were some duplicate link targets in here that produced
reStructuredText errors.

Clean up some changelog links

---

pymemcache/__init__.py

The PR allows package level import
```python
from pymemcache import Client, PooledClient, MemcacheError, ...
```
Currently its
```python
from pymemcache.client.base import Client, PooledClient
or 
from pymemcache.client import Client, MemcacheError
```

Allow classes, functions, exceptions to be conveniently imported from the package.

---

.travis.yml

This is in preparation for the Linux Infrastructure Migration:
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Remove 'sudo: false' from Travis configuration

---

ChangeLog.rst
docs/getting_started.rst
pymemcache/client/base.py
pymemcache/test/test_client.py

The client's `server` argument can now be a string containing the path
to the memcached server's UNIX domain socket.
Also document all of the connection-oriented client parameters.
This builds on the earlier work proposed in #162 and #196.

Add UNIX domain socket support

---

pymemcache/client/base.py
pymemcache/test/test_client.py

I don't currently see a way in which we would enter _connect() with an
existing socket, but let's explicitly close() first just to be safe.
This also ensures we enter the rest of the _connect() code knowing that
`self.sock is None`.
While I'm here, add better test coverage for the close() method.

Always close the existing socket on _connect()

---

pymemcache/client/base.py

Some commands are sensitive to the order of their key arguments so
revise the previous code to explicitly build a list of prefixed keys
and a dictionary of remapped keys. This generalization also lets us
remove command-specific checks from this code path.
The list of prefixed keys is used to build the command string
(preserving order).
The dictionary of remapped keys is used to map the prefixed keys from
the response to the key names that were originally provided to the
client.

Always send command keys in their original order

---

pymemcache/client/base.py
pymemcache/test/test_client.py

This command allows clients to set a new cache memory limit. The
argument is a number expressed in megabytes.
Also, treat `OK` as an acceptable response string.
This is partially based on #172.

Add support for the 'cache_memlimit' command

---

ChangeLog.rst
pymemcache/__init__.py
setup.cfg
setup.py

We can no longer import the `__version__` attribute because there is no an
implicit runtime dependency on six (as of #197), and we can't guarantee
that six is installed until *after* `setup.py` is parsed and run.
Instead, parse the `__version__ = 'x.y.z'` string from `__init__.py` to
extract the version.
Fixes #214

Parse version directly from pymemcache/__init__.py

---

ChangeLog.rst
pymemcache/__init__.py
setup.cfg
setup.py

Since setuptools 30.3.0 we can use setup.cfg to configure package
for build and distribute. These changes propose to adopt a more
modern approach to package pymemcache by using latest and stable
feature of setuptools.
Overview:
- remove python code to maintain
- introduce package metadata,
- centralize version management in package metadata

Introduce package metadata configuration by using setup.cfg

---

pymemcache/test/test_utils.py
pymemcache/test/utils.py

The actual client tries to encode unicode and if it fails
MemcacheIllegalInputError is raised. Fix the MockMemcacheClient to do
the same thing.
Fix bug #222

Handle unicode key values in MockMemcacheClient correctly

---

pymemcache/client/hash.py

This allows users to specify the noreply behavior upon creation of a HashClient like they are already able to do for Client and PooledClient.

Add default_noreply paramter to HashClient

---

pymemcache/client/base.py

Memcache can only store binary-safe values. We raise an exception when
we're unable to encode a data value using the 'ascii' codec. Improve the
exception message to make the error case clearer.
See #227

Improve ASCII encoding failure exception

---

pymemcache/client/base.py

repr()'d strings (via %r) are already quoted.

Remove redundant '' from %r values

---

.travis.yml
setup.cfg

Python 3.4 has reached end-of-life so remove it from the set of
officially supported Python versions.

Drop official support for Python 3.4

---

docs/getting_started.rst

resolves #239
Add a warning to the Best Practices section of the Getting Started doc which explains the interaction between `noreply=True` and error handling.
Also, fix a very minor typo, ``"noreply`` in a nearby line.
I understand that "WARNING" boxes are very shouty and attention-grabby, and many people are shy about using them. However, (1) in the readthedocs theme, they're orange, not red, and less harsh, and (2) this seems genuinely warning-worthy to me.
I thought for a moment about how to fit this into the client documentation, but it doesn't fit well anywhere in there, IMO.
For ease of review, here's what it looks like when rendered:

Add noreply warning to getting_started doc

---

pymemcache/client/base.py

This is a stylistic issue with little chance for actual impact. Some methods use 'ascii' verbatim and some use `self.encoding` (which defaults to 'ascii'). Those which are using `ascii` are only supposed to be accepting integer inputs, so this is actually fine.
However, the result is a potentially confusing discrepancy -- why does `Client.touch` use `ascii` while `Client.add` uses `self.encoding`? To alleviate this potential confusion, be consistent about applying `self.encoding` to all memcached commands in the base client.
This does not impact the `_check_key` func, which re-encodes potential unicode inputs as ASCII.
Bonus: this also means that if I want to be exceptionally clever (read: stupid), I could register a custom codec which does something weird and then use that in here.

Be more consistent about using Client.encoding

---

ChangeLog.rst
pymemcache/__init__.py
pymemcache/client/base.py
pymemcache/test/test_client.py

We introduced the ability to override the serializer-returned flags
values in 26f7c1b1. Unfortunately, there was a flaw in that logic which
resulted in the first item's flags being used for all later items. This
bug primarily affected set_many()'s behavior when the data dictionary
contained multiple different value types which were assigned different
per-value flags values by the serializer.
For example:
set_many({'a': 'string', 'b': 10})
If a serializer returned different flags for strings (e.g. 1) and
integer values (e.g. 2), the previous logic would have set ``flags``
to 1 the first time through the loop and repeated that value for the
second item, instead of using 2.
This was the intended behavior when ``flags`` was explicitly passed to
set_many(), but not for the default case where …

Fix flags when setting multiple values at once

---

ChangeLog.rst
pymemcache/client/base.py
pymemcache/test/test_client.py

After the conversation on #240 , I'm starting to change my mind on whether or not it's even worthwhile to continue to support callers using `expire="1"` and the like. That usage is not documented, and supporting it doesn't really make things that much better for callers.
If a caller tries to send
- a fractional expiration time
- a string for the "incr" command
- delay=None (instead of delay=0)
The pymemcache base client will now catch these usage mistakes and throw a MemcacheIllegalInputError.
Although there are existing valid (but undocumented) usages of the current string conversion behavior, the docs state that these values are supposed to be ints. Now if a non-int value is used, it will immediately trigger an error.
This behavior is superior to the prior behavior especially in the …

Check integer input values to Client methods

---

pymemcache/client/base.py

For `add()`, `replace()`, `cas()`, and `delete()`, if `noreply` is True (or if it is unset and `self.default_noreply` is True), the return value is always True.
See #253, #254

Clarify noreply + self.default_noreply behavior

---

README.rst

I was reading through the documentation and noticed a minor
inconsistency in the naming of the python-memcached library. This
commit updates the library name to reflect the real library we're
referencing.

trivial: update library name

---

pymemcache/test/test_utils.py
pymemcache/test/utils.py

So that MockMemcacheClient is more complete and can be used for testing
prepend and append cases.

Add prepend and append support to MockMemcacheClient

---

pymemcache/client/hash.py
pymemcache/test/test_client_hash.py
pymemcache/test/test_integration.py

Adds the `touch` method to `pymemcache.client.hash.HashClient`. This method already exists in `pymemcache.client.base.Client` & `pymemcaache.client.base.PooledClient`

Add touch method to HashClient

---

ChangeLog.rst
pymemcache/__init__.py

The code is in good shape for our next major release so this just
updates the changelog and package version.

Start the version 3.0.0 release process

---

pymemcache/test/utils.py

Adding a `clear` method to `MockMemcacheClient` as a way to reset/clear the mock cache.

Adding clear method to MockMemcacheClient

---

pymemcache/test/utils.py

Refactoring the client mock to better mimic the actual behavior of the real client. In this particular case deserialize and serialize are deprecated but still supported in Pymemcahce version 3.0.0. The Mock should also depreciate these items rather than completely removing these kwargs in order to keep consistency between the client mock and real mock.

Enforcing consistency between the client mock and real client so they reflect the same behavior

---

pymemcache/client/base.py
pymemcache/client/hash.py
pymemcache/test/test_client.py
pymemcache/test/utils.py

Our current MockMemcacheClient doesn't throw an error if a key has a
space, and given MockMemcacheClient can be consumed by downstream
things, we want it to act as close to the real client as possible.
Rename _check_key to check_key_helper so we aren't importing a private
function.

Update MockMemcacheClient to reuse check_key

---

pymemcache/client/hash.py
pymemcache/test/test_client_hash.py

Hey, 
I haven't opened an issue for that as I believe it's easier to show failing tests.
Looks like `clients/hash` behaves incorrectly when dead server comes back alive - it's never removed from `dead_clients` and thus retried indefinitely. 
Failing test and fix are visible in 35ee9de, rest of PR simply adds some test coverage and refactors existing code a little.

Fix corner case with dead server coming back alive

---

pymemcache/__init__.py
pymemcache/test/utils.py

This PR makes `MockMemcacheClient` closer to the implementation of `Client`, namely:
- Added `socket_module`, and `tls_context` parameters `__init__()`
- Added `socket_module`, `sock`, and `tls_context` attributes
- Added `replace()`
- Added `cas()` (which raises `MemcacheClientError` as `cas_enabled` is false for this `MockMemcacheClient`)
- Added `touch()`
- Added `cache_memlimit()`
- Added `version()`
- Added `flush_all()` (internally calling `clear()`)
- Added `quit()`
- Added `close()`
- Refactored `set()` to have default `flags` set to None
- Refactored `set_many()` to follow `Client`'s implementation (always return `[]` when `noreply` is True, else return the keys that were not inserted)
- Refactored `decr()` to have a similar implementation to `incr()` (also taking in account …

Align Client and MockMemcacheClient to ease third-party testing #279

---

pymemcache/client/base.py
pymemcache/client/hash.py
pymemcache/test/test_client.py
pymemcache/test/test_client_hash.py

The user can subclass Client (e.g to add telemetry or logging), and have
their custom client class used by PooledClient and HashClient to create
new clients.

Make PooledClient and HashClient able to use a custom client class

---

docs/getting_started.rst

Reading the documentation I just realize that there is a small detail that can be improved.
There is a missing `=` on one of the examples, it is added on the pull request.

Adding a missing assignment on the example of getting a value

---

pymemcache/client/base.py

Looks like a copy / paste error in the docs, but the documentation for `decr` talked about incrementing the value, not decrementing it

Updated docs for decrement

---

pymemcache/__init__.py
pymemcache/client/__init__.py
pymemcache/client/base.py
pymemcache/client/hash.py
pymemcache/test/test_client_hash.py

Some of these tweaks will smooth some of the API incompatibilities encountered when implementing django/django#13310.
This also addresses the main wart highlighted in #291.

Various tweaks to aid implementation of cache backend in Django.

---

pymemcache/client/base.py
pymemcache/client/hash.py
pymemcache/test/test_client_hash.py

`HashClient` didn't support using paths to UNIX sockets and passing them to the underlying client.
With these changes it should also be possible to use a mix of UNIX sockets and `(host, port)` 2-tuples.

Added support for UNIX sockets in HashClient.

---

.github/workflows/ci.yml
setup.cfg
test-requirements.txt

- https://pythoninsider.blogspot.com/2020/10/python-35-is-no-longer-supported.html
- https://pythoninsider.blogspot.com/2020/10/python-390-is-now-available-and-you-can.html

Drop Python version 3.5 and add 3.9

---

ChangeLog.rst

IPv6 may be used in preference to IPv4 when passing a domain name as the
host if an IPv6 address can be resolved for that domain.
Closes #301

Highlight an important part of the IPv6 support

---

.github/workflows/ci.yml

GitHub Actions appears to be busted with regard to IPv6-based localhost
resolution between containers. This prevents us from successfully
connecting to our memcached service containers.
We can't resolve this by using `--server` (and `--tls-server`) to
explicitly specify 127.0.0.1 to force IPv4, but that unfortunately
breaks TLS certification verification because that expects 'localhost'.
We should come up with a better solution for this, but for the short
term, this unblocks the failing CI builds.

Disable IPv6 localhost resolution for CI

---

pymemcache/client/base.py
pymemcache/test/test_client.py

_check_cas() does a good job of normalizing a CAS value and raising
MemcacheIllegalInputError when fed an invalid value. We were only using
this function in the `cas is not None` path within _store_cmd().
By moving this check into cas() itself, it allows us to also raise
MemcacheIllegalInputError when `cas is None`, which can happen when this
pattern is used for a new key:
val, cas = c.gets('key')
c.cas('key', 'value', cas)
See #233

Move _check_cas() check into cas() method

---

pymemcache/client/base.py
pymemcache/test/test_client.py

According to the [Memcached Protocol](https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L1151), the no argument form of the stats command should have no trailing spaces. Currently, `b'stats \r\n'` instead of `b'stats\r\n'` is being sent to the socket which leads to a malformed response.

Removing trailing space after a command if there are no arguments.

---

pymemcache/client/hash.py
pymemcache/test/test_client_hash.py

Overlooked when UNIX socket support was added to `HashClient` in
acd962b586a4fe018a00acb7e1621be373c13c3b.
Fixes #314.

Fixed `HashClient.{get,set}_many()` with UNIX sockets.

---

pymemcache/client/hash.py
pymemcache/test/test_client_hash.py

This should fix #319 .
Some unit tests had to be changed since the data returned from `client.set_many` is different from when we iterate over `client.set` multiple times.
- `test_ignore_exec_set_many` - With the old approach if an exception occurred we could mark the individual key as failed and keep going. With `set_many` we only get a list of failed keys if no exception was thrown. Instead if `ignore_exc` is set, I chose to mark all keys as set.
- `test_set_many_unix` - It relies on the ordering of keys in a dict, which is unordered. I changed it from checking if a specific key failed, to just check a single key failed.
I don't have all the python interpreters installed on my machine, but tests pass for the following envs in tox:
- `py27`
- `py36`
- `py37`
- `py27-flake8`
- …

Use client.set_many in HashClient.

---

pymemcache/client/base.py
pymemcache/client/hash.py
pymemcache/pool.py
pymemcache/test/test_client.py

The Memcached server can be configured to drop idle connections (via the
`idle_timeout` option). When this occurs, pymemcache may still try to
use the connection, resulting in `MemcacheUnexpectedCloseError`. Hence
the need for client-side idle timeout logic.
This change was proposed in pinterest/pymemcache#114, but ultimately dropped.
The current PR uses the same approach but differs slightly in the details.

Remove idle connections from pool

---

pymemcache/client/base.py
pymemcache/test/test_client.py

This change proposes the addition of a client API wrapper for the [`shutdown` text protocol command](https://github.com/memcached/memcached/blob/c472369fed5981ba8c004d426cee62d5165c47ca/doc/protocol.txt#L1698).
Minimal example usage:
```python
from pymemcache.client.base import Client
c = Client('localhost:11211')
c.shutdown(False)
```
When shutdown is not enabled on the server:
```
<28 new auto-negotiating client connection
28: Client using the ascii protocol
<28 shutdown
>28 ERROR: shutdown not enabled
<28 connection closed.
```
```
File "driver.py", line 5, in <module>
c.shutdown(False)
File "/home/kiwi/sync/code/external/pymemcache/pymemcache/client/base.py", line 845, in shutdown
self._misc_cmd([cmd], b'shutdown', False)
File …
```

Client API for server shutdown protocol command

---

.github/workflows/ci.yml

I think the value provided by codespell is low and not worth the CPU
cycles to run it on ever change.
Also, the flake8 complexity check isn't particularly helpful (in my
opinion).

Remove codespell and flake8 complexity check

---

pymemcache/client/base.py
pymemcache/test/test_client.py

These changes allow users to activate and configure their socket keepalive.
For now users can configure:
- the enabling of their socket keepalive;
- the time the connection needs to remain idle before TCP starts sending
keepalive probes;
- the time (in seconds) between individual keepalive probes;
- the maximum number of keepalive probes TCP should send before dropping
the connection.
This could be used by users who want to handle fine grained failures and
scenarios.
Also this could be another way to handle problems more or less similar
to https://github.com/pinterest/pymemcache/issues/307
This could be in addition of the retry mechanisms
https://github.com/pinterest/pymemcache/pull/324
For now this feature only support Linux platform.
Other systems support could be added through follow …

Implement socket keepalive configuration mechanisms

---

pymemcache/client/base.py
pymemcache/test/test_client.py

During network maintenance operations or during server reboot users could
face MemcacheUnexpectedCloseError.
This kind of exception will be raised down the stack. It's a design
choice [1]. Users should manage this kind of exception.
However, at some points the opened sockets remains more or less opened
after this kind of fail on the client side [2]. It will require n+1
calls to see them recreated when the connection will be possible. That's
could be problem with services that implement several cache logics in parallel
and where their clients are based on pymemcache.
These changes simply ensure to close the socket properly. The socket
will be recreated by the client if needed.
[1] https://github.com/pinterest/pymemcache/issues/307
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1977711

Ensure us to close socket on MemcacheUnexpectedCloseError

---

.github/workflows/ci.yml
tox.ini

These changes allow us to rely on tox when we execute our linters on CI.
They centralize the way we define our jobs and targets to use them
in standardized way locally and during CI pipelines.
With these changes we are sure to execute the same commands everywhere.

Rely on tox for CI linter

---

pymemcache/client/base.py

The KeepaliveOpts's taken parameters aren't well renderer in the doc.
Their docstrings are missing.
This patch fix that.

Fix doc rendering

---

pymemcache/__init__.py

As this class aim to be used with all kind of clients it would be worth to allow to import it from the root namespace of pymemcache.
Else, without these changes, we will have to import it from `pymemcache.client.base`.
Examples without these changes:
```
>>> from pymemcache import KeepaliveOpts
File "<stdin>", line 1, in <module>
ImportError: cannot import name 'KeepaliveOpts' from 'pymemcache'
(/home/hberaud/pymemcache/pymemcache/__init
__.py)
```
Examples with these changes:
```
>>> from pymemcache import KeepaliveOpts
>>>
```

Allow us to import the KeepalivOpts from the root pymemcache namespace

---

pymemcache/client/base.py
pymemcache/test/test_client.py

These changes fix a condition for python 2.7 only.
Python 3 and python 2.7 behave differently during our key handling.
With python 3, in the case where the key is empty and where the key is not a
bytes object the concatenation [1] will fail and the execution will be stoped
with the raise of a TypeError exception.
With python 2 the concatenation is not a problem and so the execution
isn't stoped and that lead us to a problematic condition few line below [2].
Here we execute a condition with a boolean logic and an `or` operator.
That mean that if the first condition doesn't return `True` we will
execute the second condition, in this case we will compare an index of a
previous split with our original key. The problem here is that if our
key is empty then we will try to retrieve the index `0` …

[py27] Fixing a bug with bad conditions

---

docs/getting_started.rst
pymemcache/client/__init__.py
pymemcache/client/retrying.py
pymemcache/test/test_client_retry.py

Goal here is basically to help with https://github.com/pinterest/pymemcache/issues/307.
And takes inspiration from this [comment](https://github.com/pinterest/pymemcache/issues/307#issuecomment-862109935)
The idea is a thin "wrapper client" that does nothing but forward calls and retry as appropriate.
The features are as follows:
- Takes any Client or Client-like class.
- Configurable number of retries.
- Configurable sleep between retries. (Don't think it's really a good idea in a cache, but it was easy, so here we are.)
- Allows retrying only for specific Exception types.
- Allows skipping retries for specific Exception types.
I haven't written tests yet since I wanted some opinions on the interface/constructor first.
Currently the class uses `__getattr__` to pass through any …

Implement RetryingClient

---

docs/getting_started.rst

https://pymemcache.readthedocs.io/en/latest/getting_started.html#using-the-built-in-retrying-mechanism

Fix typo in doc

---

.github/workflows/ci.yml
pymemcache/client/base.py
pymemcache/client/hash.py
pymemcache/client/rendezvous.py
pymemcache/fallback.py
pymemcache/pool.py
pymemcache/serde.py
pymemcache/test/conftest.py
pymemcache/test/test_benchmark.py
pymemcache/test/test_client.py
pymemcache/test/test_client_hash.py
pymemcache/test/test_client_retry.py
pymemcache/test/test_integration.py
pymemcache/test/test_serde.py
pymemcache/test/test_utils.py
pymemcache/test/utils.py
setup.cfg
test-requirements.txt
tox.ini

End of Life information:
* 3.5 https://www.python.org/downloads/release/python-350/
* 3.4 https://www.python.org/downloads/release/python-340/
* 2.7 https://www.python.org/doc/sunset-python-2/
Remove six dependency and run pyupgrade to start using native python 3 syntax

Drop python support for 2.7, 3.4 and 3.5

---

docs-requirements.txt
docs/conf.py
tox.ini

This PR replaces the `run_apidoc` event handler with the [sphinxcontrib-apidoc](https://github.com/sphinx-contrib/apidoc) extension. It does pretty much the same thing, but it's a little more convenient. Feel free to close this PR if you don't find that useful, but personally it's saved me quite a few headaches.
Notes:
* `apidoc_separate_modules` is equivalent to the `-e` option
* `apidoc_module_dir` and `apidoc_output_dir` are relative to the documentation source dir (`/docs`)
* I updated `tox.ini` so local Sphinx builds will use the apidoc config in `conf.py` instead of separately running the `sphinx-apidoc` command
* I added a `.readthedocs.yml` to install `docs-requirements.txt`. If you already have that configured in your settings on readthedocs.org, that file can be removed.

Use sphinxcontrib-apidoc extension for readthedocs builds

---

README.rst

Hey guys,
Proposing to replace the following broken link: http://code.mixpanel.com/2012/07/16/we-went-down-so-we-wrote-a-better-pure-python-memcache-client/
This is the updated link: https://engineering.mixpanel.com/we-went-down-so-we-wrote-a-better-pure-python-memcache-client-b409a9fe07a9
Best,
Juan

Update README.rst - (broken link)

---

pymemcache/client/base.py
pymemcache/test/test_client.py
pymemcache/test/test_client_retry.py

There are small typos in:
- pymemcache/client/base.py
- pymemcache/test/test_client.py
- pymemcache/test/test_client_retry.py
Fixes:
- Should read `setting` rather than `settting`.
- Should read `collection` rather than `collectino`.
- Should read `serializer` rather than `seralizer`.
- Should read `interaction` rather than `interacction`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

pymemcache/client/base.py
pymemcache/test/test_client.py

ignore_exc should treat an error as a cache miss and default specifies
what should be returned on a miss.
Fixes issue #350

Use default for get ignore_exc

---

pymemcache/client/hash.py
pymemcache/test/test_client_hash.py

When using `HashClient` with `ignore_exc`, `get` would always return
`None` if no server is available. The other clients return the default
value in this case.
Return the default value so `HashClient` behaves like the other
clients.
Fixes a variation of issue #350

Return default from hash client

---

pymemcache/client/hash.py
pymemcache/test/test_client_hash.py

The regular client supports noreply so pass args, kwargs like for other
functions in hash client
Fixes issue #360

Support noreply for hash flush_all

---

.github/workflows/ci.yml
setup.cfg
tox.ini

Python 3.6 reached the end of its life last year.

Drop support for Python 3.6

---

.github/workflows/ci.yml
lint-requirements.txt
setup.cfg
test-requirements.txt
tox.ini

This repositions tox as the "source of truth" for all development and CI
actions.
To support this, lint and test requirements have been split into
separate sets of requirements, and a consolidated 'lint' environment now
runs all of our lint checks. This is also used by CI.

Revise tox configuration

---

pymemcache/client/base.py
pymemcache/test/test_client.py
pymemcache/test/test_client_retry.py

This also drops support for passing None as a server spec, which is
something many tests were doing out of lazy convenience. I can't think
of a reason why we'd want to support that for real world usage.

Formalize typing for server specifications

---

README.rst

Django added built-in support in 3.2: https://docs.djangoproject.com/en/3.2/releases/3.2/#pymemcache-support

Update Django paragraph

---

.github/dependabot.yml

We're only interested in automatic dependency updates for minor (not
patch) pytest versions, and we don't need to track every incremental
mypy update.

Ignore noisy dependency updates

---

pymemcache/client/base.py
pymemcache/test/test_client.py

A stat with a blank value makes the .stats() call fail with index error.  
```
memcache_connection.stats() 
File "/lib/python3.6/site-packages/pymemcache/client/base.py", line 741, in stats 
result = self._fetch_cmd(b'stats', args, False) 
File "/lib/python3.6/site-packages/pymemcache/client/base.py", line 921, in _fetch_cmd 
result[key_value[1]] = key_value[2]
IndexError: list index out of range
```
The line in question we saw that caused this:
```
b'STAT ep_initfile '
```
This fixes things to no longer blow up.   I chose to use a blank binary string instead of None because I suspect other code might make assumptions about the data being binary strings due to this bug.

Handle a blank stat value

---

pymemcache/client/base.py

Basically ensure the client only does one pass over the buffer instead of two.
Exact thread: https://github.com/pinterest/pymemcache/pull/395#discussion_r890288417

Small buffer pass optimization as discussed in #395.

---

pymemcache/client/base.py
pymemcache/test/test_client.py

This is the first step towards implementing #87.
The ElastiCache configuration command returns a multi-line reply that the current clients are incapable of reading fully, so a new method for reading the response from the socket is needed.
But since some of the required code for ElastiCache is a bit low in the client stack I thought it best to get some eyes on that part before doing the AWS specific stuff.
The reason I put it as a public method on `Client` is because any other client will need this one to send the configuration request to ElastiCache before being able to create the actual server configuration.
I have some questions/notes:
- Currently if `end_tokens` is not found in the buffer, the client will hang forever, or timeout, with a real socket connection. For the unit-test we …

Expand Client with a method for sending arbitrary commands. 

---

docs/getting_started.rst

Fixed a few grammatical and sentence construction mistakes from docs.

Fixed Typos in Docs

---

.gitignore
pymemcache/serde.py
pymemcache/test/test_benchmark.py
pymemcache/test/test_compression.py
pymemcache/test/test_integration.py
pymemcache/test/test_serde.py
test-requirements.txt

This adds a new class `CompressedSerde` which allows you to use it as an entrypoint to compression.  It defaults to using `zlib` and has immediate benefits on the size of messages stored in memcached but it also has `compress` and `decompress` as pluggable points if you want to use a stronger compression algorithm like `lz4`.

add pluggable compression serde

---

MANIFEST.in

As per https://peps.python.org/pep-0561/ add a py.typed file to let things like mypy there is inline typing information

Add py.typed file

---

pymemcache/client/base.py
pymemcache/test/conftest.py
pymemcache/test/test_integration.py

Add integration tests to reproduce the issue and add an argument to _fetch_cmd to skip the key prefix logic as needed.
Closes #430

Fix key_prefix issue with stats and cache_memlimit

---

setup.cfg

Make it easier to find the documentation from https://pypi.org/project/pymemcache/
https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls

Update project urls to include link to docs

---

test-requirements.txt

More detailed info here:
https://github.com/lericson/pylibmc/issues/284

Bump `pylibmc` version to avoid installation error while creating the dev env.

---

pymemcache/client/hash.py

This fixes different behaviour between base and hash for incr, decr: Fixes #475

Consistent behaviour for incr, decr for Hash and Base

---

docs/conf.py

By default autodocs only show class docstrings and hide __init__ https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autoclass_content https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_default_options
Make sure docstrings added to __init__ functions show up in the docs
Closes #473

Make sure __init__ functions are displayed in docs

---

README.rst
pymemcache/test/test_serde.py

Closes #479
This test was written with the assumption
that sys.maxsize is equal to 2**63 - 1 everywhere.
sys.maxsize is equal to 2**31 - 1 on a 32-bit
platforms and 2**63 - 1 on a 64-bit platforms.
See also https://docs.python.org/3/library/sys.html#sys.maxsize

fix test serde failure on 32-bit platforms

---

.github/workflows/ci.yml
docs-requirements.txt
docs/conf.py
lint-requirements.txt
pymemcache/client/base.py
pymemcache/client/retrying.py
pymemcache/pool.py
pymemcache/test/test_client_retry.py
pyproject.toml
setup.cfg
tox.ini

Minimum version of 3.9
Add up to 3.13
Build improvements

Pyupgrade to 3.9

---

pymemcache/client/ext/aws_ec_client.py
pymemcache/ext/aws_ec_client.py
pymemcache/test/test_ext_aws_ec_client.py
pymemcache/test/utils.py

Hi! I found that MR with previous implementation [stuck](https://github.com/pinterest/pymemcache/pull/548) and make a new one.
It brings new class which inherited from HashClient and allow to use AWS ElastiCache for Memcached cluster.
Resolves https://github.com/pinterest/pymemcache/issues/534

AWS Elasticache autodiscovery support 

---

pymemcache/client/base.py
pymemcache/test/test_client.py

This makes PooledClient.gets usable. Thanks in advance for looking!

PooledClient bug fix: add default, cas_default kwargs to gets

---

pymemcache/test/test_ext_aws_ec_client.py

This was causing a lint error:
./pymemcache/test/test_ext_aws_ec_client.py:41:10: F841 local variable 'mock' is assigned to but never used

Remove unused 'mock' variable
