pymemcache/client.py, pymemcache/pool.py, pymemcache/test/test_client.py
- Add a object pool that can create clients in a thread
safe manner (and release and destroy them as/when needed).
=> Create a pooled client class

README.md
Might as well add myself :smile:
=> Add harlowja to credits in README

pymemcache/pool.py
Avoid holding the pool lock while calling into
the 'after_remove' callback to ensure that no kind
of deadlock is likely to occur (say if the callback
calls back into the pool).
=> Run 'after_remove' callback outside of lock

.travis.yml
Ensure we are testing with 3.4 (as well as 3.3).
=> Add travis 3.4 builds

pymemcache/client.py, pymemcache/test/test_client.py
On Python 2.7 and 3.4, `sock.recv()` returns EINTR when it interrupted by signal.
https://gist.github.com/methane/59781ec74e00402e4c6b
Some web server uses signal to manage workers. So pymemcache should retry recv() when EINTR.
(Python 3.5 retries automatically. See https://www.python.org/dev/peps/pep-0475/ )
=> Retry when sock.recv() raises EINTR

ChangeLog.rst, MANIFEST.in, setup.py
This introduces a ChangeLog that shows up in the readme.  This isn't perfect because currently README is Markdown format which pypi doesn't support, so things like the build badge don't show up on pypi:
https://pypi.python.org/pypi/pymemcache
I want to introduce this without fixing that because I want to add ChangeLog entries in #59 and I'll fix it there since I have README changes to add in it as well.
=> Introduce ChangeLog

README.rst
=> README states it's available on pip with badge and instructions

pymemcache/client/__init__.py
=> Also expose exceptions in backwards compatible way

pymemcache/client/base.py, pymemcache/test/test_client.py, pymemcache/test/utils.py
Resolves #78 
Have only added to the base `Client` at this time, will extend to other classes if accepted as a feature suggestion.
=> Add default_noreply to Client

pymemcache/client/base.py, pymemcache/test/test_integration.py
=> Security sanitize key 

ChangeLog.rst, pymemcache/__init__.py, setup.cfg
Added bumpversion support, and release notes. It has been uploaded to pypi
=> Release 1.3.6 to pypi

docs/conf.py
This will build the docs automatically when they go through the readthedocs process, as explained here
https://github.com/rtfd/readthedocs.org/issues/1139
=> Automate doc building

README.rst, pymemcache/__init__.py, setup.cfg
=> Pre release 137

docs/getting_started.rst
Added a section of the docs to explain the constraints around the keys used
=> Doc about keys

README.rst
You can either run the tests manually or use tox.
=> Update README to mention tox

.travis.yml, ChangeLog.rst, tox.ini
Fixes https://github.com/pinterest/pymemcache/issues/132
=> Drop support for pypy3 

ChangeLog.rst, pymemcache/__init__.py, setup.cfg
=> Release 1.4.1 

ChangeLog.rst, pymemcache/__init__.py, setup.cfg
Going to deploy and push 1.4.3 to pypi, build the docs and then point to it from the pinterest repos
=> Release 143

pymemcache/test/test_client_hash.py
Also wrap a line that exceeds 80 characters.
=> Introduce some missing .set() assertions

pymemcache/serde.py
We made a change that was backwards incompatible and didn't realize until after the merge. ALthough we are still interested in upgrading our pickle method, we need to think it through further in order to preserve backwards compatibilty
=> Reverse backwards compatible change

ChangeLog.rst, pymemcache/__init__.py, setup.cfg
fixes https://github.com/pinterest/pymemcache/issues/173
=> New release 144

pymemcache/client/base.py
=> typo: alwais -> always

README.rst
This renders much better across multiple screen resolutions.
=> Switch to an SVG Travis-CI build badge

README.rst
=> Mention django-pymemcache in the README

pymemcache/client/base.py, pymemcache/test/test_client.py, pymemcache/test/utils.py
added flags in client functions to provide support for extra memcached operations.
=> add flags in client functions

pymemcache/client/base.py, pymemcache/test/test_client.py
extract _value_helper() from _fetch_cmd() to support customized value extraction logic.
=> extracted _extract_value() from _fetch_cmd()

pymemcache/client/hash.py, pymemcache/test/test_client_hash.py
pass the encoding from the hashed client to the added servers
=> HashClient pass encoding servers

.github/CODEOWNERS, docs-requirements.txt, docs/conf.py, pymemcache/serde.py
This also updates some of our documentation metadata and authorship.
=> Upgrade to Sphinx 3 for generated documentation

docs/getting_started.rst
=> Mention PooledClient in the documentation

ADOPTERS.md, README.rst, docs/getting_started.rst, pymemcache/client/base.py, pymemcache/client/hash.py, pymemcache/test/test_client.py, pymemcache/test/test_client_hash.py
=> Added support for connections over IPv6.

pymemcache/test/test_client.py
=> Removed print() in test.

docs/getting_started.rst
Code snippets of my previous changes (https://github.com/pinterest/pymemcache/pull/221) aren't well rendered.
https://pymemcache.readthedocs.io/en/latest/getting_started.html#interacting-with-pymemcache
=> Fix doc rendering

pymemcache/test/test_client.py
9551dfd0 introduced a call to `socket.getaddrinfo()` to support IPv6, but
we never added an implementation of that function to MockSocketModule.
This resulted in some tests making "live" `socket.getaddrinfo()` calls
because of the default `MockSocketModule.__getattr__` implementation
(which we need to forward other module attribute lookups).
Fixes #325
=> Provide a mock implementation of socket.getaddrinfo

MANIFEST.in
Closes https://github.com/pinterest/pymemcache/issues/330
=> MANIFEST.in: Add test data and docs

tox.ini
Trivial changes to add code coverage.
=> adding code coverage

ChangeLog.rst, pymemcache/__init__.py
=> Prepare the v3.5.0 release

README.rst
I've changed my GitHub username. This updates the link to my GitHub profile. Thanks.
=> Update link to my GitHub profile.

pymemcache/pool.py, test-requirements.txt
Black and its style guide are now officially stable. Future releases
will allow incremental adoption of new style changes via a new --preview
system.
=> Upgrade to Black 22.1.0 (from 22.11b1)

README.rst, docs/getting_started.rst
By request from @jparise in #359.
I just wrote about the same content and style I did in the issue. But If you guys would rather have the format changed. Let me know.
I also took the liberty of adding my name to credits in the README. Hope that is okay.
=> Add more documentation on HashClient to getting started.

pymemcache/client/base.py, pymemcache/client/hash.py, pymemcache/pool.py
Continue to improve the type annotation coverage
=> Add more type annotations

ChangeLog.rst, pymemcache/__init__.py
=> 4.0.0 Release

setup.cfg
Follow up to #435 because I forgot the comment when I merged
=> Add link to issue tracker as well

README.rst, pymemcache/client/base.py, pymemcache/client/hash.py, pymemcache/test/test_client.py, pymemcache/test/test_client_hash.py, pymemcache/test/test_integration.py
=> Support for Gat (Get and Touch), Support passing server key in a tuple

lint-requirements.txt, pymemcache/client/base.py, pymemcache/client/retrying.py, pymemcache/test/test_client.py, pymemcache/test/utils.py
https://github.com/psf/black/blob/main/CHANGES.md
Run latest version of black to fix formatting issues
=> Upgrade to black 23.3.0

.github/workflows/ci.yml
python 3.7 is no longer supported.
=> Update ci.yml and remove python 3.7

pymemcache/client/hash.py, pymemcache/test/test_client_hash.py
For Issue #549 
Added stats method to the HashClient class  
Do let me know if there are any comments
=> Added stats method to the HashClient class
